notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: UxdrnvqTSxcQvJLYS9pZvZP3G9aIhkXbrgnSwnEq6fHxs25xW5Mqxkt9ZOdegBGBzikVtbJvxY+96WoN1HxPEzXHH/txWHqzNBxNp/npE+jQrQrWAv5YpieM7EqXkr/JJPWViUs8qd1w5yBXNDq2FukaQKtHkAXOlbknGo6pHuC4jG5uNEoorAv2z33XlGhv8KBL4H62jROIS+8Ixx0YWvepfIhWZ3rxuqdcDQwUcoc4LwBhajfEo/+wXNp8RLnCUGWb1rCoQhlNVhfno6VysfBkrKVz8r27PolRE5xDFvc/vzx81ya9xKK21EGxSX6Zq+vRftq/IlwtP0PBXVj+BZlU3AAvg9iB8CPoYM+otiURJEZddR8hIy3SM/svjep8li8UL2TSEzYOXz6dVxA62jkiBJCqtWxyaLPdV4DozU1c4Voqs/V2Ggz2NdqbvqlFu94F6uCNHDluvJDNN6WB8KpLMWqrCbasTSoRPKUoIXgzi8RUMyker8VREsmfhnwYWntwTY5pQ2SlZdv9cvRhMKtc1IhbYLhoW4jkxTn3VaIGPdU3pRJ0k6+VICA4BZmgfQmfPdA8xr8FqUMx7HgBqkqniljF2Mw1T/1JtkUup/HDUbbEh37K97Yz98ewDMTZmYezbWNY2vGWK0TM2h2Bt/hN32kOy53VDTBtRXk9kVY=
  api_key:
    secure: UEYUgZLm6p7i7u5zyfaNqOpNalUPbw8ibVHaekVKwHXDU8ys0GeWz7eYrD2TbiaXKNhsx7pT+ufjbRFRFjzrDfE6c4velvjypNGP8qd+lzNMCyI1mbSuxOgYonEdjJT75gkF9QBDF7IrDelAml1eSBSAK0OVtqxkIEbNRmJst+pD3UV3aTGKzCLmhMxGSI/WBohsNIF7ObXVs6Jr4uGWBAhbicJuxNvOUHnLkAcrlYqAOnSjHcjzN/WecI6tqW9+trvkerjOBq5HNMszJQDpqo+Rhi06NWZucVfEODtbuNls6o1dK9mV4bhkmYLbr2i4/EPPN0eg8CwF9jGauSBV9Pg4SD2TZxkaGa7MBgDe9Dlc9iHeejCjdFbAfD4axBfsvrH5y2aXwl+2DO2z1DMHYZk9biU4dOwze7IecIYeFvUqWmWVvVyGVw8198mIk7OMqmSmRJnXQdUPpaVdqffHQX2woP4jO55UxrwVpaQMavaWIUaDm3pV8UJuYRDBiS0IIKTo9NB1H+KgyRQZKTPDvHRdWpyuKf8q3PrXpHTocM7x7mwrtXU6QZHUsKX63IE7VofXHONe9/137023MDTeXemFzGDmndimoeXF4qK10q8CIHfiOyJP7aiuQFO503mBcGUBGt3F9sT/6TaV2WHV0SHsQDCbvtsBncyzoR570XY=
  on:
    tags: true
